version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: sessionz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - springboot-db-net
    ports:
      - '5001:5432'
    restart: unless-stopped
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9092:9092'
    networks:
      - springboot-db-net
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sessionz
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
     

networks:
   springboot-db-net:

    
    